### ISSUE TITLE
Type search should use the locale-specific type string

### ISSUE THREAD

**Issue by dbalatero** [falling-fruit/falling-fruit-mobile#10]
@ezwelty What are your thoughts on this? I was thinking the type search should use the new locale-specific type string.

<img width="397" alt="screenshot 2017-03-04 21 15 37" src="https://cloud.githubusercontent.com/assets/59429/23584762/daaa72cc-011f-11e7-8660-3760108fbdcb.png">

**Comment by ezwelty** [comment]
@dbalatero Yes, the locale-specific full type names "Common name [Scientific name]" should now be injected into the fullscreen type select as you point out, as well as the add_location form type dropdown (also used for editing).

**Comment by dbalatero** [comment]
@ezwelty Okay, I'll add another story for `add_location` as well.

**Comment by dbalatero** [comment]
Done: https://github.com/falling-fruit/falling-fruit-mobile/issues/13

**Comment by dbalatero** [comment]
Closed by #14
